version: '3.9'

services:
  db_postgres:
    image: postgres
    ports:
      - 5438:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456789
    # extra_hosts:
    #   - host.docker.internal:192.168.1.4

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db_postgres

  app:
    image: golang-learning-app:1.0
    ports:
      - 8080:8080
    depends_on:
      - db_postgres

volumes:
  postgres_data:
    driver: local
